u=10
v=100
range=$((v-u+1))
a=$(($(($RANDOM%$range))+u))
b=$(($(($RANDOM%$range))+u))
c=$(($(($RANDOM%$range))+u))
d=$(($(($RANDOM%$range))+u))
e=$(($(($RANDOM%$range))+u))
sum=$(($a+$b+$c+$d+$e))
average=$(($sum/5))
echo "Sum = " $sum
echo "Average = " $average